<?php 
$data = $this->getShowData(); 
$page = ceil($data['total'] / 3); 
unset($data['total']);
$productId = $data['product_id'];
unset($data['product_id']);
?>
<?php if (!empty($data)) { ?>
<?php $mobile = Mage_Util::isMobile(); if (!$mobile) { ?>
<link rel="stylesheet" href="/media/nmred/css/reviewbox.css">
<link rel="stylesheet" href="/media/nmred/css/jquery-ui.css">
<script type="text/javascript" src="/media/nmred/js/cufon.js"></script>
<script type="text/javascript" src="/media/nmred/js/Zapfino_italic_400.font.js"></script>
<script type="text/javascript" src="/media/nmred/js/jquery-ui-1.8.16.custom.min.js"></script>
<script type="text/javascript" src="/media/nmred/js/jquery.easing.js"></script>
<script type="text/javascript" src="/media/nmred/js/jquery.lofjsidernews.js"></script>
<script type="text/javascript" src="/media/nmred/js/reviewbox.js"></script>
<div class="slider-container">
	<h5>CUSTOMER REVIEW</h5>
	<div class="reviewbox">
		<div class="reviewlistbox" style="height: auto;text-align: left;">
			<div id="review" class="reviewlist" style="display: block;">
				<?php foreach ($data as $key => $value) { ?>
				<div class="colbox">
					<div class="starbox five"></div>
					<div class="ct">
						<?php foreach ($value['imgs'] as $k => $img) { ?>
							<a href="<?php echo $img['big_img'];?>" class="reviewthumb <?php if ($k != 0) {echo 'hide';}?>" rel="<?php echo $k;?>">
								<img src="<?php echo $img['img'];?>">
							</a>
						<?php }?>
						<?php echo $value['context'];?>
						<a href="javascript:void(0);" class="readmore" rel="<?php echo $value['review_id']?>">Read More</a>
					</div>
					<div class="username"><?php echo $value['username'];?></div>
					<div class="date"><?php echo date('Y-m-d', $value['create_time']);?></div>
				</div>
				<?php } ?>
				<?php if ($page >= 2) { ?>
				<div class="pagination review">
					<div class="links" style="margin-left: 373px;" id="review_page_links" max_page="<?php echo $page;?>">
						<b class="prevpage">PREV</b>
						<?php for($i = 1; $i < $page; $i++) {?>
						<?php if ($i == 1) {echo '<b></b>';}?>
						<a id="review_page_<?php echo $i;?>" product_id="<?php echo $productId;?>" href="javascript:void(0);" rel="<?php echo $i;?>"></a>
						<?php } ?>
						<a id="review_page_next" product_id="<?php echo $productId;?>" rel="1" href="javascript:void(0);" class="nextpage">NEXT</a>
					</div>
				</div>
				<?php } ?>
			</div>
		</div>
	</div>
</div>

<script>
var globalReviewTotal = <?php echo $page;?>;
<!--{{{-->
jQuery(document).on('click', '.pagination a', function() {
	var objtmp = this;
	jQuery.ajax({
		url: '/newreview/index/review?page=' + jQuery(this).attr('rel') + '&product_id=' + jQuery(this).attr('product_id'),
		type: 'post',
		dataType: 'json',
		success: function(result) {
			if (result.status == 0) {
				return;
			}
			var _html = [];
			for (var i = 0; i < result.data.length; i++) {
				_html.push('<div class="colbox">');
				_html.push('<div class="starbox five"></div>');
				_html.push('<div class="ct">');
				var item = result.data[i];
				for (var j = 0; j < item['imgs'].length; j++) {
					if (item['imgs'][j].big_img) {
						_html.push('<a href="' + item['imgs'][j].big_img + '" class="reviewthumb ');
						if (j != 0) {
							_html.push(' hide');
						}
						_html.push('" rel="' + j + '">');
						_html.push('<img src="' + item['imgs'][j].img + '">')
						_html.push('</a>');
					}
				}
				_html.push(item['context']);
				_html.push('<a href="javascript:void(0);" class="readmore" rel="' + item['review_id'] + '">Read More</a>');
				_html.push('</div>');
				_html.push('<div class="username">' + item['username'] + '</div>');
				_html.push('<div class="date">' + item['create_time'] + '</div>');
				_html.push('</div>');
			}
			
			var current   = jQuery(objtmp).attr('rel');
			var productId = jQuery(objtmp).attr('product_id');
			_html.push('<div class="pagination review"><div class="links" style="margin-left: 373px;" id="review_page_links">');
			if (current == 0) {
				_html.push('<b class="prevpage">PREV</b>');
			} else {
				_html.push('<a product_id="' + productId + '" href="javascript:void(0);" rel="' + (parseInt(current) - 1) + '" id="review_page_prev" class="prevpage">PREV</a>');
			}
			for (var i = 0; i < globalReviewTotal; i++) {
				if (current != i) {
					_html.push('<a id="review_page_' + i + '" product_id="' + productId + '" href="javascript:void(0);" rel="' + i + '"></a>');
				} else {
					_html.push('<b></b>');
				}
			}
			if (current == parseInt(globalReviewTotal) - 1) {
				_html.push('<b class="nextpage">NEXT</b>');
			} else {
				_html.push('<a id="review_page_next"  product_id="' + productId + '" rel="' + (parseInt(current) + 1) + '" href="javascript:void(0);" class="nextpage">NEXT</a>');
			}		
			_html.push('</div></div>');
			_html = _html.join('');
			jQuery("#review").html(_html);
			Cufon.replace(['#review .colbox .username'], {
				hover: true,
				fontFamily: 'Zapfino'
			});
		}
	});
});
<!--}}}-->
<!--{{{-->

jQuery(document).on('click', '.readmore', function() {
	jQuery.ajax({
		url: '/newreview/index/info?review_id=' + jQuery(this).attr('rel'),
		type: 'post',
		dataType: 'json',
		success: function(result) {
			if (result.status == 0) {
				return;
			}
			console.info(result);
			var data = result.data;
			var _html = [];
			_html.push('<div class="reviewdetail left" style="display: block;text-align: left;">');
			if (!data.imgs.length) {
				_html.push('<div class="imglist ct" style="height:200px">');
			} else {
				_html.push('<div class="imglist ct" style="height:auto">');
			}
			_html.push('<div class="imglisttitle">PHOTO LIST</div>');
			for (var i = 0; i < data.imgs.length; i++) {
				_html.push('<a href="' + data.imgs[i].big_img + '" class="reviewthumb" rel="0">');
				_html.push('<img src="' + data.imgs[i].img  + '"></a>');
			}
			_html.push('</div>');
			_html.push('<div class="starbox five"></div>');
			console.info(data.context);
			_html.push('<div class="detailtext">' + data.context + '</div>');
			_html.push('<div class="username">' + data.username + '</div>');
			_html.push('<div class="date">' + data.create_time + '</div>');
			_html.push('<a href="javascript:void(0);" class="goback">Review List</a>');
			_html.push('</div>');
			jQuery('.reviewlistbox').hide();
			jQuery('.reviewdetail').remove();
			jQuery('.reviewlistbox').after(_html.join(''));
			Cufon.replace(['.reviewdetail .username'], {
				hover: true,
				fontFamily: 'Zapfino'
			});
		}
	});
});

jQuery(document).on('click', '.goback', function() {
	jQuery('.reviewlistbox').show();
	jQuery('.reviewdetail').hide();
});

<!--}}}-->
<!--{{{-->
jQuery(document).on('click', '.reviewbox .reviewlistbox .colbox .ct a.reviewthumb, .reviewdetail .imglist a.reviewthumb', function(){
	var obj = jQuery(this);
	floatGrayBox();
	var measureboxheight = 480;
	if(((jQuery(window).height() - measureboxheight) / 2) > 0){
		var mtop = ((jQuery(window).height() - measureboxheight) / 2) - 60;
	}else{
		var mtop = 30;
	}
	var htmlstr = '';

	htmlstr += '<div class="reviewimagebox" style="width:640px;height:480px;background-color:FFFFFF;">';
	htmlstr += '<div id="reviewimagelist" class="lof-slidecontent" style="width:640px;height:480px;">';
	htmlstr += '<div class="preload"><div></div></div>';
	htmlstr += '<div class="main-slider-content" style="width:640px;height:480px;"><ul class="sliders-wrap-inner">';
	obj.parent('.ct').find('.reviewthumb').each(function(){
		htmlstr += '<li><img src="' + jQuery(this).attr('href') + '" /></li>';
	});
	htmlstr += '</ul></div>';
	htmlstr += '<div class="navigator-content"><div class="button-next">Next</div><div class="navigator-wrapper"><ul class="navigator-wrap-inner">';
	obj.parent('.ct').find('img').each(function(){
		htmlstr += '<li><img src="' + jQuery(this).attr('src') + '" /></li>';
	});
	htmlstr += '</ul></div><div class="button-previous"></div></div>';
	htmlstr += '<div class="button-control"><span></span></div>';
	htmlstr += '</div></div>';

	jQuery('.floatgraybox .messagebox').addClass('reviewimagefloatingbox');
	jQuery('.floatgraybox .messagebox').append(htmlstr);
	jQuery('.floatgraybox .messagebox').css({'margin-top': jQuery(document).scrollTop() + mtop + 'px',
		'margin-left': (jQuery('body').width() - 630) / 2 + 'px'});
	jQuery(window).resize(function(){
		jQuery('.floatgraybox .messagebox').css({'margin-top': jQuery(document).scrollTop() + mtop +
			'px'});
	});
	jQuery(window).scroll(function(){
		jQuery('.floatgraybox .messagebox').css({'margin-top': jQuery(document).scrollTop() + mtop +
			'px'});
	});
	jQuery('.floatgraybox').height(jQuery('body').height()).fadeIn(function(){
		var buttons = {
			previous:jQuery('#reviewimagelist .button-previous') ,
			next:jQuery('#reviewimagelist .button-next')
		};
		jQuery('#reviewimagelist').lofJSidernews({
			interval : 3000,
			direction : 'opacitys',
			easing : 'easeInOutExpo',
			duration : 1200,
			startItem: Number(obj.attr('rel')),
			auto : true,
			maxItemDisplay : 4,
			navPosition : 'horizontal', // horizontal
			navigatorHeight: 74,
			navigatorWidth : 80,
			mainWidth: 640,
			buttons: buttons
		});
	});
	return false;
});
<!--}}}-->
</script>
<?php } else { ?>
<link rel="stylesheet" href="/media/nmred/css/reviewbox_mobile.css">
<script type="text/javascript" src="/media/nmred/js/reviewbox_mobile.js"></script>
<div class="reviewbox">
    <div class="tl">
        <div class="tltext">CUSTOMER REVIEW</div>
    </div>
    <div class="reviewlistbox" style="height: auto;">
		<div id="review" class="reviewlist">
			<div class="review-pic-box carousel-wrapper product-tab col-06">
				<div class="review-pic listbox row" style="transform: translate3d(0px, 0px, 0px);">
					<ul class="review-pic-content products-grid" style="">
						<?php foreach ($data as $key => $value) { ?>
						<li class="item colbox" id="review_li_index_<?php echo $key;?>" style="margin-right: 0px; width: 394px;<?php if ($key != 0) echo 'display:none;'; ?>">
							<div class="ct picture">
								<?php foreach ($value['imgs'] as $k => $img) { ?>
								<a href="javascript:void(0);" class="reviewthumb" style="<?php if ($k != 0) {echo 'display:none';}?>" rel="<?php echo $k;?>">
									<img src="<?php echo $img['img'];?>" rel="<?php echo $img['big_img'];?>">
								</a>
								<?php }?>
							</div>
							<div class="ct text">
								<div class="starbox five"></div>
								<div class="username"><?php echo $value['username'];?></div>
								<div class="content"><?php echo $value['context'];?></div>
								<div class="content-full"><?php echo $value['lcontext'];?></div>
								<div class="date"><?php echo date('Y-m-d', $value['create_time']);?></div>
								<a href="javascript:void(0);" class="view-next" rel="<?php echo $key;?>">View Next</a>
								<a href="javascript:void(0);" class="readmore" rel="<?php echo $value['review_id']?>">Read More</a>
							</div>
						</li>
						<?php }?>
					</ul>
				</div>
				<div class="product-slide-bg"></div> <div class="reviews-count"><a href="javascript:void(0);" class="view-prev" rel="0" id="review_list_prev">&lt;</a><span id="review_list_total"><?php echo count($data); ?></span> Reviews<a id="review_list_next" href="javascript:void(0);" class="view-next" rel="0">&gt;</a></div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php } ?>
<?php } ?>
