<img id="showorder_list" style="display:none;" action="showorder/list"/>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-edit"></i>晒单管理</div>
				<div class="actions">
					<a action="showorder/add" id="add_showorder" class="btn green">
						<i class="icon-pencil"></i> 添加
					</a>
					<div class="btn-group">
						<a class="btn green" href="#" data-toggle="dropdown">
						<i class="icon-cogs"></i> 操作
						<i class="icon-angle-down"></i>
						</a>
						<ul class="dropdown-menu pull-right">
							<li><a href="#" style="color:#ccc" id="mod_menu"><i class="icon-pencil"></i>修改</a></li>
							<li><a href="#" style="color:#ccc" id="del_menu"><i class="icon-trash"></i>删除</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-hover table-bordered" id="showorder_data">
					<thead>
						<tr>
							<th style="width:8px;"><input type="checkbox" class="group-checkable" data-set="#showorder_data .checkboxes" /></th>
							<th>晒单标题</th>
							<th>描述信息</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="js/app/showorder.js"></script>
<script>
var mxShowOrder = new ShowOrder();
mxShowOrder.setThisName('mxShowOrder');
mxShowOrder.init();
</script>
