<link rel="stylesheet" href="css/jquery.fileupload.css">
<link rel="stylesheet" href="css/jquery.fileupload-ui.css">
<link href="umeditor/themes/default/css/umeditor.css" type="text/css" rel="stylesheet">
<img id="newreview_list" style="display:none;" action="newreview/list"/>
<div class="row-fluid">
	<div class="span12">
		<!-- BEGIN SAMPLE FORM PORTLET-->
		<div class="tabbable tabbable-custom boxless">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#tab_1" data-toggle="tab">上传图片</a></li>
				<li><a class="" href="#tab_2" data-toggle="tab">评论信息</a></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="tab_1">
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption"><i class="icon-reorder"></i>添加评论图片</div>
							<div class="tools">
								<a href="javascript:;" class="reload"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<form id="fileupload" action="newreview/upload" method="POST" enctype="multipart/form-data">
								<!-- Redirect browsers with JavaScript disabled to the origin page -->
								<noscript><input type="hidden" name="redirect" value=""></noscript>
								<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
								<div class="row-fluid fileupload-buttonbar">
									<div class="span7">
										<!-- The fileinput-button span is used to style the file input field as button -->
										<span class="btn green fileinput-button">
										<i class="icon-plus icon-white"></i>
										<span>Add files...</span>
										<input type="file" name="files[]" multiple>
										</span>
										<button type="submit" class="btn blue start">
										<i class="icon-upload icon-white"></i>
										<span>Start upload</span>
										</button>
										<button type="reset" class="btn yellow cancel">
										<i class="icon-ban-circle icon-white"></i>
										<span>Cancel upload</span>
										</button>
										<button type="button" class="btn red delete">
										<i class="icon-trash icon-white"></i>
										<span>Delete</span>
										</button>
										<input type="checkbox" class="toggle fileupload-toggle-checkbox">
									</div>
									<!-- The global progress information -->
									<div class="span5 fileupload-progress fade">
										<!-- The global progress bar -->
										<div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
											<div class="bar" style="width:0%;"></div>
										</div>
										<!-- The extended global progress information -->
										<div class="progress-extended">&nbsp;</div>
									</div>
								</div>
								<!-- The loading indicator is shown during file processing -->
								<div class="fileupload-loading"></div>
								<br>
								<!-- The table listing the files available for upload/download -->
								<table role="presentation" class="table table-striped">
									<tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
								</table>
							</form>
					<div class="span12">
						<script id="template-upload" type="text/x-tmpl">
							{% for (var i=0, file; file=o.files[i]; i++) { %}
							    <tr class="template-upload fade">
							        <td class="preview"><span class="fade"></span></td>
							        <td class="name"><span>{%=file.name%}</span></td>
							        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
							        {% if (file.error) { %}
							            <td class="error" colspan="2"><span class="label label-important">Error</span> {%=file.error%}</td>
							        {% } else if (o.files.valid && !i) { %}
							            <td>
							                <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
							            </td>
							            <td class="start">{% if (!o.options.autoUpload) { %}
							                <button class="btn">
							                    <i class="icon-upload icon-white"></i>
							                    <span>Start</span>
							                </button>
							            {% } %}</td>
							        {% } else { %}
							            <td colspan="2"></td>
							        {% } %}
							        <td class="cancel">{% if (!i) { %}
							            <button class="btn red">
							                <i class="icon-ban-circle icon-white"></i>
							                <span>Cancel</span>
							            </button>
							        {% } %}</td>
							    </tr>
							{% } %}
						</script>
						<!-- The template to display files available for download -->
						<script id="template-download" type="text/x-tmpl">
							{% for (var i=0, file; file=o.files[i]; i++) { %}
							    <tr class="template-download fade">
							        {% if (file.error) { %}
							            <td></td>
							            <td class="name"><span>{%=file.name%}</span></td>
							            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
							            <td class="error" colspan="2"><span class="label label-important">Error</span> {%=file.error%}</td>
							        {% } else { %}
							            <td class="preview">
							            {% if (file.thumbnail_url) { %}
							                <a class="fancybox-button" data-rel="fancybox-button" href="{%=file.url%}" title="{%=file.name%}">
							                <img src="{%=file.thumbnail_url%}">
							                </a>
							            {% } %}</td>
							            <td class="name">
							                <a href="{%=file.url%}" title="{%=file.name%}" data-gallery="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
							            </td>
							            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
							            <td colspan="2"></td>
							        {% } %}
							        <td class="delete">
							            <button class="btn red" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.delete_with_credentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
							                <i class="icon-trash icon-white"></i>
							                <span>Delete</span>
							            </button>
							            <input type="checkbox" class="fileupload-checkbox hide" name="delete" value="1">
							        </td>
							    </tr>
							{% } %}
						</script>
					</div>
						</div>
					</div>
				</div>
				<div class="tab-pane" id="tab_2">
					<div class="portlet box blue">
						<div class="portlet-title">
							<div class="caption"><i class="icon-reorder"></i>添加评论信息</div>
							<div class="tools">
								<a href="javascript:;" class="reload"></a>
							</div>
						</div>
						<div class="portlet-body form">
							<!-- BEGIN FORM-->
							<form action="#" id="add_form" class="form-horizontal">
								<div class="control-group">
									<label class="control-label">用户名<span class="required">*</span></label>
									<div class="controls">
										<input type="text" name="username" class="span6 m-wrap" />
										<input type="hidden" name='product_id' value="<?php echo $product_id; ?>" id="product_id"/>
										<input type="hidden" name='entity_id' value="<?php echo $entity_id; ?>" id="entity_id"/>
										<span class="help-inline" for="username"></span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" name="context">评论信息</label>
									<div class="controls">
										<script type="text/plain" id="context" style="width:1000px;height:240px;">
										</script>
										<span class="help-inline"></span>
									</div>
								</div>
								<div class="form-actions">
									<button type="button" id="form_submit" class="btn blue">提交</button>
									<button type="button" id="form_reset" class="btn">重置</button>
								</div>
							</form>
							<!-- END FORM-->
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="js/jquery.fancybox.pack.js"></script>
<script src="js/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="js/canvas-to-blob.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="js/jquery.fileupload.js"></script>
<!-- The File Upload file processing plugin -->
<script src="js/jquery.fileupload-fp.js"></script>
<!-- The File Upload user interface plugin -->
<script src="js/jquery.fileupload-ui.js"></script>
<script src="js/jquery.toggle.buttons.js"></script>
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]><script src="js/jquery.xdr-transport.js"></script><![endif]-->
<!-- END:File Upload Plugin JS files-->
<!-- END PAGE LEVEL PLUGINS -->
<script src="js/app.js"></script>
<script src="js/form-fileupload.js"></script>
<link rel="stylesheet" type="text/css" href="css/bootstrap-wysihtml5.css"/>
<link rel="stylesheet" type="text/css" href="css/bootstrap-toggle-buttons.css"/>
<script type="text/javascript" charset="utf-8" src="umeditor/umeditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="umeditor/umeditor.min.js"></script>
<script type="text/javascript" src="umeditor/lang/zh-cn/zh-cn.js"></script>
<script src="js/app/newReview.js"></script>
<script>
var mxNewReview = new NewReview();
mxNewReview.setThisName('mxNewReview');
mxNewReview.initAdd();
</script>
