<img id="newreview_list" style="display:none;" action="newreview/list"/>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-edit"></i>评论管理</div>
				<div class="actions">
				</div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-hover table-bordered" id="newreview_data">
					<thead>
						<tr>
							<th>商品ID</th>
							<th>url</th>
							<th>操作</th>
							<th>操作</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="js/app/newReview.js"></script>
<script>
var mxNewreview = new NewReview();
mxNewreview.setThisName('mxNewreview');
mxNewreview.init();
</script>
