<img id="newreview_reviewlist" style="display:none;" action="newreview/reviewlist"/>
<input type="hidden" value="<?php echo $product_id; ?>" id="product_id"/>
<input type="hidden" value="<?php echo $entity_id; ?>" id="entity_id"/>
<div class="row-fluid">
	<div class="span12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption"><i class="icon-edit"></i>评论列表</div>
				<div class="actions">
				<a action="newreview/add?product_id=<?php echo $product_id;?>&entity_id=<?php echo $entity_id;?>" id="add_review" class="btn green">
						<i class="icon-pencil"></i> 添加
					</a>
					<div class="btn-group">
						<a class="btn green" href="#" data-toggle="dropdown">
						<i class="icon-cogs"></i> 操作
						<i class="icon-angle-down"></i>
						</a>
						<ul class="dropdown-menu pull-right">
							<li><a href="#" style="color:#ccc" id="mod_menu"><i class="icon-pencil"></i>修改</a></li>
							<li><a href="#" style="color:#ccc" id="del_menu"><i class="icon-trash"></i>删除</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="portlet-body">
				<table class="table table-striped table-hover table-bordered" id="newreviewlist_data">
					<thead>
						<tr>
							<th style="width:8px;"><input type="checkbox" class="group-checkable" data-set="#newreviewlist_data .checkboxes" /></th>
							<th>EntityId</th>
							<th>ProductId</th>
							<th>评论信息</th>
							<th>用户</th>
							<th>评论时间</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="js/app/newReview.js"></script>
<script>
var mxNewreviewList = new NewReview();
mxNewreviewList.setThisName('mxNewreviewList');
mxNewreviewList.initList();
</script>
